#!/usr/bin/env bash

do_backup (){

repository=$1

restic --repo ${repository} \
  backup \
  /etc/wpa_supplicant.conf \
  /home/palo/.ssh \
  /home/palo/.gnupg \
  /home/palo/.gitconfig \
  /home/palo/.password-store \
  /home/palo/finance \
  /home/palo/deployment \
  /home/palo/.task \
  /home/palo/.timewarrior \
  /home/palo/.config/bugwarrior \
  /home/palo/.config/youtube-dl \
  /home/palo/.hpodder \
  /home/palo/books/ \
  /home/palo/Sport \
  /home/palo/memo \
  /home/palo/.Rack \
  --exclude /home/palo/.Rack/plugins \
  /home/palo/private \
  --exclude /home/palo/private/lost+found \
  /home/palo/music-projects/ \
  --exclude /home/palo/music-projects/.BitwigStudio \
  /home/palo/.ssb/ \
  --exclude=".ssb/blobs*"

}

backup_local () {
  local usb=$1
  if [[ -d ${usb} ]];
  then
    echo "backup : ${usb}"
    do_backup ${usb}
  fi
}

backup_s3 () {
  local target=$1
  ping 1.1.1.1 -c 1 > /dev/null
  result1=$?
  ping 8.8.8.8 -c 1 > /dev/null
  result2=$?
  if [[ $result1 == 0  && $result2 == 0 ]]; then
    source ~/.ssh/aws.key
    echo "backup : s3"
    do_backup s3:s3.amazonaws.com/${target}
  fi
}

backup_kruck() {
  local target=$1
  ping kruck -c 1 > /dev/null
  result1=$?
  if [[ $result1 == 0  ]]; then
    echo "backup : kruck"
    do_backup sftp:root@kruck.private:${target}
  fi
}


backup_local /backup/restic
backup_local /media/platin1/backup/restic
backup_local /media/frog1/backup/restic

backup_kruck /home/backup/workhorse

backup_s3    backup-private-palo-de/restic

